# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e910bfddc6c8b78edae77bc87298949919b1b90b784066bc384e985ed37b3585236ac1439d8e8c04a921dcb6395d91316f65c02b4798cc71a3f087f7b31a73c9

test:
  secret_key_base: 8a12386d7bfd2e64d070dc1521d8f55c3deb2186b0c04f74d0b04907fe8738c907d242b41f7a40254d456a848ba84f5a4e9253f365a3f4360b0f200e6d8c61c5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
